### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/getmac#27]
Improve type assurances by adding mypy-style type annotations to functions and variables in a sensible manner. These must be done as comments and **not** Python 3.5+ runtime type annotations! We have to preserve compatibility with Python 2.6 and 2.7.

[mypy docs](https://mypy.readthedocs.io/en/stable/)
[mypy Python 2 code](https://mypy.readthedocs.io/en/latest/python2.html#type-checking-python-2-code)
[Python 2 typing "cheat sheet"](https://mypy.readthedocs.io/en/stable/cheat_sheet.html#cheat-sheet-py2)
[PEP 484 "type comments"](https://www.python.org/dev/peps/pep-0484/#type-comments)

### Tasks
* [ ] Add type annotations to functions
* [ ] Add type annotations to variables
* [ ] Test with mypy

**Comment by GhostofGoes** [comment]
@kritokrator Sure have at it

**Comment by GhostofGoes** [comment]
No, it's a string with the arguments

**Comment by GhostofGoes** [comment]
This is done
